-- 1. Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image_url text
);

alter table products enable row level security;

create policy "Public Read Access" on products
  for select using (true);

insert into products (name, price) values
  ('Burger Supreme', 12.99),
  ('Sushi Platter', 24.50),
  ('Vegan Bowl', 15.00);

-- 2. Create Cart Table
create table if not exists cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references products not null,
  quantity int default 1 check (quantity > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, product_id)
);

alter table cart_items enable row level security;

create policy "Users can view their own cart items" on cart_items
  for select using (auth.uid() = user_id);

create policy "Users can insert into their own cart" on cart_items
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own cart items" on cart_items
  for update using (auth.uid() = user_id);

create policy "Users can delete their own cart items" on cart_items
  for delete using (auth.uid() = user_id);
