-- Create the products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image_url text
);

-- Enable Row Level Security (good practice)
alter table products enable row level security;

-- Create a policy to allow anyone to read products
create policy "Public Read Access" on products
for select using (true);

-- Insert sample data
insert into products (name, price) values
  ('Burger Supreme', 12.99),
  ('Sushi Platter', 24.50),
  ('Vegan Bowl', 15.00);
