-- Create cart_items table
create table if not exists cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references products not null,
  quantity int default 1 check (quantity > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, product_id)
);

-- Enable RLS
alter table cart_items enable row level security;

-- Policies
create policy "Users can view their own cart items" on cart_items
  for select using (auth.uid() = user_id);

create policy "Users can insert into their own cart" on cart_items
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own cart items" on cart_items
  for update using (auth.uid() = user_id);

create policy "Users can delete their own cart items" on cart_items
  for delete using (auth.uid() = user_id);
